filetype plugin indent on
set backspace=indent,eol,start
" show existing tab with 4 spaces width
set tabstop=4
" when indenting with '>', use 4 spaces width
set shiftwidth=4
" On pressing tab, insert 4 spaces
set expandtab
set mouse=a
set clipboard=unnamed
syntax on
